name: Build SCSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Sass
      run: sudo apt-get install -y sassc

    - name: Compile SCSS to CSS
      run: sass --no-source-map VAR1/styles/styles.scss VAR1/styles/css/styles.css

    - name: Commit CSS
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add VAR1/styles/css/styles.css
        git commit -m 'Compile SCSS to CSS'
        git push
